# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: 'windows-2022'

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'AnyCPU'
  - name: buildConfiguration
    value: 'Release'
  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    platform: '$(buildPlatform)'
    solution: '**/JeniusApps.Common.Uwp.csproj'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copying nupkg files to staging directory'
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copying snupkg files to staging directory'
  inputs:
    Contents: '**/*.snupkg'
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
